# Generated by Django 3.0 on 2019-12-15 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Languajes',
            new_name='Language',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='paradim',
            new_name='paradigm',
        ),
    ]
